/**
 * Mirror of `CustomerSupport.Application.Common.Security.Permissions`.
 * These strings must match the server exactly: the JWT carries them as `perm` claims and both
 * `permissionGuard` and `HasPermissionDirective` compare against them verbatim.
 */
export const PERMISSIONS = {
  customers: {
    view: 'customers.view',
    create: 'customers.create',
    update: 'customers.update',
    delete: 'customers.delete',
    manageContacts: 'customers.contacts.manage',
    viewNotes: 'customers.notes.view',
    manageNotes: 'customers.notes.manage',
    viewHistory: 'customers.history.view',
    export: 'customers.export',
  },
  tickets: {
    view: 'tickets.view',
    viewAll: 'tickets.view.all',
    create: 'tickets.create',
    update: 'tickets.update',
    delete: 'tickets.delete',
    assign: 'tickets.assign',
    changeStatus: 'tickets.status.change',
    escalate: 'tickets.escalate',
    reply: 'tickets.reply',
    internalNote: 'tickets.note.internal',
    merge: 'tickets.merge',
    viewHistory: 'tickets.history.view',
    manageCategories: 'tickets.categories.manage',
    managePriorities: 'tickets.priorities.manage',
    manageStatuses: 'tickets.statuses.manage',
  },
  channels: {
    view: 'channels.view',
    manage: 'channels.manage',
    manageWebForms: 'channels.webforms.manage',
    handleLiveChat: 'channels.livechat.handle',
  },
  workspace: {
    viewOwnTasks: 'workspace.tasks.view',
    manageTasks: 'workspace.tasks.manage',
    assignTasks: 'workspace.tasks.assign',
    manageQuickReplies: 'workspace.quickreplies.manage',
    manageGlobalQuickReplies: 'workspace.quickreplies.manage.global',
    collaborate: 'workspace.collaborate',
  },
  sla: {
    view: 'sla.view',
    managePolicies: 'sla.policies.manage',
    manageCalendars: 'sla.calendars.manage',
    manageAssignmentRules: 'sla.assignment.manage',
    manageEscalationRules: 'sla.escalation.manage',
  },
  knowledgeBase: {
    view: 'kb.view',
    author: 'kb.author',
    publish: 'kb.publish',
    delete: 'kb.delete',
    manageCategories: 'kb.categories.manage',
    viewAnalytics: 'kb.analytics.view',
  },
  ai: {
    useSuggestions: 'ai.suggestions.use',
    viewUsage: 'ai.usage.view',
    configure: 'ai.configure',
    manageChatbot: 'ai.chatbot.manage',
  },
  reports: {
    viewTickets: 'reports.tickets.view',
    viewSla: 'reports.sla.view',
    viewAgentPerformance: 'reports.agents.view',
    viewSatisfaction: 'reports.satisfaction.view',
    viewDashboards: 'reports.dashboards.view',
    manageDashboards: 'reports.dashboards.manage',
    schedule: 'reports.schedule',
    export: 'reports.export',
  },
  administration: {
    viewUsers: 'admin.users.view',
    manageUsers: 'admin.users.manage',
    manageRoles: 'admin.roles.manage',
    managePermissions: 'admin.permissions.manage',
    viewAuditLogs: 'admin.audit.view',
    manageSettings: 'admin.settings.manage',
    manageBranches: 'admin.branches.manage',
    manageDepartments: 'admin.departments.manage',
    manageTeams: 'admin.teams.manage',
    manageBranding: 'admin.branding.manage',
  },
  integrations: {
    view: 'integrations.view',
    manage: 'integrations.manage',
    manageApiClients: 'integrations.apiclients.manage',
    manageWebhooks: 'integrations.webhooks.manage',
    viewSyncLogs: 'integrations.synclogs.view',
  },
} as const;
