using CustomerSupport.Domain.Common;
using CustomerSupport.Domain.Enums;

namespace CustomerSupport.Domain.Customers;

/// <summary>
/// The customer profile aggregate (Customer Management / Customer profiles).
/// Owns contacts, notes and the interaction timeline.
/// </summary>
public class Customer : BaseEntity, IAuditable, ISoftDeletable, ITenantScoped
{
    public Guid? BranchId { get; set; }

    /// <summary>Human-readable reference (<c>CUS-000123</c>), generated by <c>ICustomerNumberGenerator</c>.</summary>
    public string Code { get; set; } = string.Empty;
    public CustomerType Type { get; set; } = CustomerType.Individual;

    public LocalizedText DisplayName { get; set; } = new();
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? CompanyName { get; set; }
    /// <summary>National ID for individuals, Commercial Registration number for companies.</summary>
    public string? NationalIdOrCr { get; set; }
    public string? TaxNumber { get; set; }

    /// <summary>Denormalised from the primary <see cref="CustomerContact"/> rows for fast list/search.</summary>
    public string? PrimaryEmail { get; set; }
    public string? PrimaryPhone { get; set; }

    /// <summary>BCP-47 tag (<c>ar</c> / <c>en</c>) driving portal UI and outbound message language.</summary>
    public string PreferredLanguage { get; set; } = "ar";
    public ChannelKey PreferredChannel { get; set; } = ChannelKey.Email;
    public string? TimeZoneId { get; set; }

    /// <summary>Service tier (e.g. <c>Standard</c>, <c>Gold</c>); may select a different SLA policy.</summary>
    public string? Tier { get; set; }
    public Guid? AccountManagerId { get; set; }
    public bool IsActive { get; set; } = true;
    /// <summary>Blocks new inbound tickets from this customer without deleting history.</summary>
    public bool IsBlocked { get; set; }
    public string? BlockedReason { get; set; }

    /// <summary>Maintained by the CSAT pipeline; average of responded surveys, 1–5.</summary>
    public decimal? SatisfactionScore { get; set; }
    public DateTimeOffset? LastInteractionAt { get; set; }

    public ICollection<CustomerContact> Contacts { get; set; } = new List<CustomerContact>();
    public ICollection<CustomerNote> Notes { get; set; } = new List<CustomerNote>();
    public ICollection<Interaction> Interactions { get; set; } = new List<Interaction>();

    public DateTimeOffset CreatedAt { get; set; }
    public Guid? CreatedById { get; set; }
    public DateTimeOffset? ModifiedAt { get; set; }
    public Guid? ModifiedById { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DeletedAt { get; set; }
    public Guid? DeletedById { get; set; }
}
